[project]
name = "aikanojo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.6.4",
    "openai>=2.16.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
]
